### ISSUE TITLE
Variation in the SSTab statement

### ISSUE THREAD

**Issue by kaoecoito** [uwol/vb6parser#10]
The TabDlg.SSTab object uses a variation in the declaration that generates errors in the parse of frm files.
Here is an example of a layout.
       TabCaption (0) = "& Location"
       Tab (0) .ControlEnabled = -1 'True
       Tab (0) .Control (0) = "lblEst"
       Tab (0) .Control (0) .Enabled = 0 'False

**Comment by uwol** [comment]
Hi, I have problems reproducing that error and therefore would like to write a unit test first.

Can you please provide me with a complete file, which provokes that error? Then I can derive the unit test and provide a fix.

Thanks!

**Comment by kaoecoito** [comment]
Hello,
Attached is a sample form created using the SSTab component that behaves differently from the other Visual Basic components.
To use this component simply activate the component called "Microsoft Tabbed Dialog Control 6.0 (SP6)" in the Visual Basic toolbar.
I am available if you need more information.
Thank you.

[Form1.zip](https://github.com/uwol/vb6parser/files/1177206/Form1.zip)

**Comment by uwol** [comment]
Thanks again! (Hopefully) fixed in commit https://github.com/uwol/vb6parser/commit/b209a8f036cacc45291289e606577349222c0a5e. I have added the form as a unit test.
