### ISSUE TITLE
get*Calls returns type members with the same name

### ISSUE THREAD

**Issue by zbagz** [uwol/vb6parser#4]
MyClass.cls
```
Public Function MyFunction() As String
    MyFunction = "MyFunction"
End Function

Public Sub MySub()
    DoEvents
End Sub
```
MyModule.bas
```
Public Type MyType
    MyFunction As String
    MySub As String
End Type

Public Sub Test()
    Dim MyTypeInstance As MyType
    
    MyTypeInstance.MyFunction = "MyModule" ' not detected as a call - fine
    MsgBox MyTypeInstance.MyFunction ' detected as a call - wrong
    
    MyTypeInstance.MySub = "MySub" ' not detected as a call - fine
    MsgBox MyTypeInstance.MySub ' detected as a call - wrong
End Sub
```
VB6Parser
```
Program program = new io.proleap.vb6.asg.runner.impl.VbParserRunnerImpl().analyzeDirectory(inputDirectory);

for (FunctionCall functionCall : program.getClazzModule("MyClass").getFunction("MyFunction").getFunctionCalls()) {
    ParserRuleContext ctx = (ParserRuleContext)functionCall.getCtx();
    System.out.println("Function Call: " + ctx.getText() + " (line: " + ctx.start.getLine() + ") (pos: " + ctx.start.getCharPositionInLine() + ")");
}

for (SubCall subCall : program.getClazzModule("MyClass").getSub("MySub").getSubCalls()) {
    ParserRuleContext ctx = (ParserRuleContext)subCall.getCtx();
    System.out.println("Sub Call: " + ctx.getText() + " (line: " + ctx.start.getLine() + ") (pos: " + ctx.start.getCharPositionInLine() + ")");
}
```
Result
```
Function Call: MyFunction (line: 13) (pos: 26)
Sub Call: MySub (line: 16) (pos: 26)
```
Expected Result
```
Emtpy result as there're no calls.
```

If I'm not wrong this error happens with getFunctionCalls, getSubCalls, getPropertyGetCalls, getPropertyLetCalls, and getPropertySetCalls functions.

By the way, I'm using this to create a small obfuscator applying source code transformations to prevent abusers from cracking or abusing my software. 

This parser is just perfect, thank you so much for saving me countless hours of learning and research time.

**Comment by uwol** [comment]
Thanks, you have found a bug. I have committed a fix and [unit test](https://github.com/uwol/vb6parser/blob/43706002435be96c60f3f2c09dbda483c5643dcc/src/test/java/io/proleap/vb6/asg/call/member/MemberCallTest.java#L28) based on your code snippets. If problems persist, please let me know!

Side Note: Over the weekend I had to change the method signature of `VbParserRunner` a little bit by replacing `VbParserRunner.analyzeDirectory` with `VbParserRunner.analyzeFiles`. So the caller now has to provide all of the program's files instead of the program directory (e. g. by calling `List<File> files = Lists.newArrayList(directory.listFiles())` before).

**Comment by zbagz** [comment]
Thank you Ulrich. I can confirm this is now fixed for my code snippet. However, I've continued testing today and I've found some other cases where this happens as well:

- Inside with statements - I've modified the test [here](https://github.com/zbagz/vb6parser/commit/2c0780598e138db1a74dc2614e03bb6f1294be87).

- With control properties or procedures (not quite sure if these are ComplexTypes but I guess they are BaseTypes) - I've added a new "control call" test [here](https://github.com/zbagz/vb6parser/commit/6e318c0a38b170647642c8012a0a33221590948e).

I'll keep adding more tests if I see new errors. Thanks again.

**Comment by uwol** [comment]
Ok, fixes are committed:

- Inside WITH: Fixed the parser. Added a WITH statement in the [test resource](https://github.com/uwol/vb6parser/blob/61cb69764137501e555143dc90aa3d73f8cb3776/src/test/resources/io/proleap/vb6/asg/call/member/MyModule.bas#L16) and modified the [unit test](https://github.com/uwol/vb6parser/blob/61cb69764137501e555143dc90aa3d73f8cb3776/src/test/java/io/proleap/vb6/asg/call/member/MemberCallTest.java#L63).
- Control (non-member) properties or procedures: Fixed the parser. Added your [test resources](https://github.com/uwol/vb6parser/blob/61cb69764137501e555143dc90aa3d73f8cb3776/src/test/resources/io/proleap/vb6/asg/call/nonmember/MyModule.bas#L4) and the [unit test](https://github.com/uwol/vb6parser/blob/61cb69764137501e555143dc90aa3d73f8cb3776/src/test/java/io/proleap/vb6/asg/call/nonmember/NonMemberCallTest.java#L35).

If you find anything else, please let me know!

**Comment by zbagz** [comment]
Thanks. I've added some new failing cases [here](https://github.com/zbagz/vb6parser/commit/093a05ce2da68f1abd5247cc48d0a3e36e543db0).

**Comment by uwol** [comment]
Ok, for the failing cases I added a fix and extended the [unit test](https://github.com/uwol/vb6parser/blob/87e8c98e9aa8d6a9c8df946a8d1e1ebcf31305e6/src/test/resources/io/proleap/vb6/asg/call/nonmember/MyModule.bas#L10) from your snippets.

I also added your changes regarding arrays inside WITH statements. Now, `MyFunction` ist called a fourth time, so the [test has been adjusted](https://github.com/uwol/vb6parser/blob/87e8c98e9aa8d6a9c8df946a8d1e1ebcf31305e6/src/test/java/io/proleap/vb6/asg/call/member/MemberCallTest.java#L63).

These cases are somewhat more complex, so I hope I did get them correctly. If not, please let me know!

**Comment by zbagz** [comment]
Awesome! Just added a couple more of those tricky ones that I've found today:

- Select Case, For and While-Wend Loops inside WITH statements [here](https://github.com/zbagz/vb6parser/commit/9931b95d5a8807e9c2f381aa7c556d21c0fbef57#diff-9383662983da4fc264c4b9d10aeb91b8R21).

- Member calls using "Me" keyword inside classes [here](https://github.com/zbagz/vb6parser/commit/9931b95d5a8807e9c2f381aa7c556d21c0fbef57#diff-f928d5c790cfceef04a3504ab147d205R6

- getArgCalls missing arrays, but only those mentions with parenthesis, [example and tests here](https://github.com/zbagz/vb6parser/commit/1f26a528a5d72ff39048847f4c94286b2746a06e#diff-f8da43d21fe51a49cca97cd73a864fbeR13).

**Comment by uwol** [comment]
Should be fixed now. I have added your snippets in a restructured form to [the master](https://github.com/uwol/vb6parser/tree/bd5eb0840ec28f09ae38b5d85cf9827aa720408d/src/test/java/io/proleap/vb6/asg/call/type). Thanks again.

**Comment by zbagz** [comment]
Great! I've just added a new failing test for getVariableCalls [here](https://github.com/zbagz/vb6parser/commit/2a49111f460262f944c2ae67029b879fd64b6135), pretty much the same problem with arrays but for getVariableCalls instead. Thanks!

**Comment by uwol** [comment]
Ah, got it. There is the special call type `ArrayCall` for these cases, which was not linked to its corresponding variable. Should be fixed now. Please note, that `ArrayCall` now is a subclass of `VariableCall`.

**Comment by zbagz** [comment]
Today I found 2 new ones inside WITH statements:

- Class member calls [missing](https://github.com/zbagz/vb6parser/commit/85dde0d2968c63cdc98ee0ff17b1b0ff4f2bad41#diff-152ef37484889aa542ffbb28f5ce3d5cR72) the ones called within a module that also contains the same member name [defined](https://github.com/zbagz/vb6parser/commit/85dde0d2968c63cdc98ee0ff17b1b0ff4f2bad41#diff-de74bbbfca2e236c0368ded415fbe927R1).

- Class member calls [missing](https://github.com/zbagz/vb6parser/commit/85dde0d2968c63cdc98ee0ff17b1b0ff4f2bad41#diff-152ef37484889aa542ffbb28f5ce3d5cR106) when the exact member name is in use by 2 different classes. Test resource [here](https://github.com/zbagz/vb6parser/commit/85dde0d2968c63cdc98ee0ff17b1b0ff4f2bad41#diff-99c78edb1eed465b6e795a83f8b018a2R4). Curious thing to note is that when using ClassA instead of ClassB within the WITH statement the parser returns the expected result, but the other way around (as shown in test resource) fails.

Hope my examples are clear enough. These are somewhat weird cases I guess. Thank you.

**Comment by uwol** [comment]
Your examples are very clear, thanks for your preparations! The problematic calls were explicit calls, i.e. calls with leading `CALL`. Should be fixed now.

**Comment by uwol** [comment]
I assume, all calls are fixed now. If you find any other defect calls, feel free to open this or a new ticket. Thanks for your contributions!

**Comment by zbagz** [comment]
I'm sorry for the delay, I couldn't work last week. I've added a new test that fails on class members calls depending on the order they were submitted to the parser.

On the exact same test, using [this order](https://github.com/zbagz/vb6parser/commit/acf1c8a2ea29a310fbbb25c4f8d9e1ecce53eef1#diff-296e8ec65b50b3eab8956a385f97dd72R92) passes just fine but [this one](https://github.com/zbagz/vb6parser/commit/acf1c8a2ea29a310fbbb25c4f8d9e1ecce53eef1#diff-296e8ec65b50b3eab8956a385f97dd72R136) fails. Thanks!

**Comment by zbagz** [comment]
I've noticed something similar happening to Enum's as well. When both, an enum and a class, share members with the same name [this](https://github.com/zbagz/vb6parser/commit/30c2b82a081f211ac4f4b7eb95e59c98b6c67361#diff-296e8ec65b50b3eab8956a385f97dd72R177) test fails depending on which one gets declared first.

For instance, declaring the enum first and then the global class instance (as shown [here](https://github.com/zbagz/vb6parser/commit/30c2b82a081f211ac4f4b7eb95e59c98b6c67361#diff-335d45ae777575dcf6db08f3f8febd4cR8)), getFunctionCalls for "Play_Sound" returns 2, when there's only 1 function call, and the other one is the enum member.

As far as I've been testing this only happens inside a case such as [this one](https://github.com/zbagz/vb6parser/commit/30c2b82a081f211ac4f4b7eb95e59c98b6c67361#diff-8a795e7f174df08a8967fe25b4bea61dR53), while [this other one](https://github.com/zbagz/vb6parser/commit/30c2b82a081f211ac4f4b7eb95e59c98b6c67361#diff-8a795e7f174df08a8967fe25b4bea61dR50) works just fine.

**Comment by uwol** [comment]
Ok, these seem to be more complicated member calls. I'll be back in office at 12.6. and provide a fix in that week.

**Comment by nitroai** [comment]
Hi zbagz, thanks for issuing! You found 2 bugs:

- Bug 1 occurred, if a type or enumeration was used/called in module A, before module B containing the type/enumeration declaration had been processed. The fix is, that now type/enumeration declarations from all modules are processed first.
- Bug 2 occurred, if enumeration constants and procedures with identical names were defined. In that case the collision resolver followed incorrect precedence rules. The fix is, that precedence rules and enum constant lookups have been adapted.

I have committed your complete integration test. Thank you.

**Comment by uwol** [comment]
Hi zbagz, thanks for issuing! You found 2 bugs:

- Bug 1 occurred, if a type or enumeration was used/called in module A, before module B containing the type/enumeration declaration had been processed. The fix is, that now type/enumeration declarations from all modules are processed first.
- Bug 2 occurred, if enumeration constants and procedures with identical names were defined. In that case the collision resolver followed incorrect precedence rules. The fix is, that precedence rules and enum constant lookups have been adapted.

I have committed your complete integration test. Thank you.

**Comment by zbagz** [comment]
Hi Ulrich. Thank you for taking the time to commit these fixes!

I've continued testing today and I think I've found some other cases where something similar happens.

[Test A](https://github.com/zbagz/vb6parser/commit/c2e5602b8debce2b79f6d63cd99a922f4f4e486a) shows a failing case where enum members get mistaken for class functions.

[Test B](https://github.com/zbagz/vb6parser/commit/b676ac3a19b9f2bb02f3b8219ab91bfaac85b703#diff-523c14b641815e7f01968a319815f45cR8) shows a failing case when there's a private variable inside a class sharing the same name as a global variable inside a module.

[Expanded](https://github.com/zbagz/vb6parser/commit/d39db099e9eb3bd13c38289f3dfe1484e358cee2#diff-702a94c690b286bd998efc759550efcfR13) Test A containing a case where enum members get mistaken for [public class variable](https://github.com/zbagz/vb6parser/commit/d39db099e9eb3bd13c38289f3dfe1484e358cee2#diff-4d22c0e88c6c39228fabf01747018dddR3).

Added a [Test C](https://github.com/zbagz/vb6parser/commit/9ed6e99c2158ca8fcfb96d0907d4154fcf554d8d) showing a some cases where getPropertyGet/LetCalls are missing.

Thanks for your help!

**Comment by uwol** [comment]
Ok, fixed Test A (adjusted precedence) and Test B (added visibility checks). Thanks for the more compact/concise test scenarios. Short/specific tests help me a lot to identify the underlying problem.

I will check Expanded Test A and Test C in the next days.

**Comment by uwol** [comment]
Ok, Expanded Test A was already fixed together with Test A.

Test C identified a new bug: Only the last member call in a left hand side implicit members call statement may be a property let. All other preceding member calls can only be property gets (or variables etc.). Fixed that, too.

As soon as we have found and fixed all of these edge cases, I think we can call ourselves real VB 6.0 language specialists :smile:

**Comment by zbagz** [comment]
You got it! These latest fixes solved most of the errors that were showing up in my transformed source (it's a medium-sized codebase with around 400 modules). So, yeah, this is almost perfect.

I've added a last [Test D](https://github.com/zbagz/vb6parser/commit/70cd2ddb312f387eb8a4592dae517e2378f3c0b1), showing a minor case that I've just noticed. [Public variable](https://github.com/zbagz/vb6parser/commit/70cd2ddb312f387eb8a4592dae517e2378f3c0b1#diff-0564031bccd58f20d65db8070bcbc4c5R3) mistaken for enum member inside it's own class procedures.

By the way, it'd be nice to support the full CP-1252 charset for [identifiers](https://github.com/uwol/vb6parser/blob/master/src/main/antlr4/io/proleap/vb6/VisualBasic6.g4#L2076). It's probably not the best idea to use some of these characters in identifiers but they're perfectly valid. For instance:
`Dim óôõö÷øùúûüýþŸ¡¢¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿àáâãäåæçèéêëìíîïÐñò×ßacdeGhijklnOœrsštuwyzžbƒfp As Byte`

I'm not sure what is the right thing to do in this case but maybe it's worth adding the most common ones such as accented vowels, diaeresis, ñ, Ñ, ç and Ç if you're working with spanish or french people.

I'll let you know if I see something else, but I don't think it'll be anytime soon. :yum:

Thanks for all the hard work and effort you've put into creating this great parser. And all the best with your ProLeap service, looks very promising and no dubt you're the right guy to run it. :wink:

**Comment by uwol** [comment]
Thanks! Yes, we are building a code transformation service on top of those grammars. CP-1252 for identifiers should not be that complicated, I will take a look.

Currently, the precedence order of elements with colliding names is as follows:

- enumeration member
- variable
- constant
- property get/let/set
- ...

This precedence order is expected by the previously defined tests [EnumConstantCollision2Test](https://github.com/uwol/vb6parser/blob/510ad05c2af8d5db154a4a0e62c452c20d194802/src/test/java/io/proleap/vb6/asg/integration/enumconstant2/EnumConstantCollision2Test.java#L54) and [TypeMemberCallByScalarTest](https://github.com/uwol/vb6parser/blob/510ad05c2af8d5db154a4a0e62c452c20d194802/src/test/java/io/proleap/vb6/asg/integration/overrides/TypeMemberCallByScalarTest.java#L198). They expect  the enumeration member before of the variable, e.g in case of `cmdPlay` and `Close_Window`.

To make your test D pass, I would have to change the precedence order as follows:

- variable
- constant
- enumeration member
- property get/let/set
- ...

Currently, I do not have a VB6 compiler at hand to check the proper precedence order, or if any other aspects have to be taken into account. Can you please check, which of the both precedence orders is the correct one? I can fix the order immediately, then.

**Comment by zbagz** [comment]
Sure, I'm not even close to ANTLR newbie, but I've been trying to figure this out. I thought precedence order was only related to scope.

I'd say the first one in the list should be variables as you said since they are the most "low-scope" thing you can declare inside a procedure. And for the remaining ones the order shouldn't matter, since you can only have 1 of these declared in the same scope with colliding names:

* constant
* property get/let/set
* function/sub
* enumeration member

now, If I have

Class.cls

```
Private Const Hello As Byte = 0

Public Sub Whatever()
    Dim Hello As Byte: Hello = 1
    MsgBox Hello ' this returns 1, fine
End Sub
```

but now if I have

Module.bas
`Public Const Hello As Byte = 0`

and then in Class.cls
```
Private Enum myEnum
    Hello = 1
End Enum

Public Sub Whatever()
    MsgBox Hello ' this actually returns 1, but if constants have a lower precedence order and therefore considered before enum members, then this "Hello" would be mistaken as a constant -- considering no scope is taken into account
End Sub
```

I hope I'm wrong, and scope does get taken into account. If that's the case then the second order you proposed should be the correct one.

Hope this helps. Let me know if I can "contribute" with something else. Thanks!

**Comment by uwol** [comment]
Ok, you are right. I got it by your example and analysis of the compiler:

The call precedence order seems to be:

- variable IN SAME MODULE
- constant IN SAME MODULE
- enumeration member IN ANY MODULE
- variable PUBLIC IN ANY MODULE
- constant PUBLIC IN ANY MODULE
- property get/let/set
- ...

I committed a fix. The unit test provided by you passes.

Thanks again!

**Comment by zbagz** [comment]
I've been testing the compiled version of my transformed source code and everything went well but I noticed that I forgot to include arguments in the precedence order list. Otherwise, tests [such as this one](https://github.com/zbagz/vb6parser/commit/7cd2165926bc8e99176de0e868df7c39a1c4cc2c#diff-d27e728ac5656f85c6633f2f252dabe2R44) fail if there's an argument name with the same name as an enum member.

I think the order now should be

* variable in same procedure
* argument in same procedure

* public/private variable in same module
* public/private constant in same module
* public/private enum member in same module
* public/private property get/let/set in same module
* public/private sub/function in same module

* public variable in any module
* public constant in any module
* public enum member in any module
* public property get/let/set in any module
* public sub / function in any module

* ...

Does that make sense? What do you think? Thanks!

**Comment by nitroai** [comment]
I fixed the arg problem and added your test. Thanks again, unit tests are the best and future-proof way to stabilize these problems.

Your order looks good! Currently, the precedence order given by you is not implemented 100% in that way in vb6parser, as for example for enum members it is ignored, whether they are defined in the same module. I will check, how the official compiler behaves.

**Comment by uwol** [comment]
I fixed the arg problem and added your test. Thanks again, unit tests are the best and future-proof way to stabilize these problems.

Your order looks good! Currently, the precedence order given by you is not implemented 100% in that way in vb6parser, as for example for enum members it is ignored, whether they are defined in the same module. I will check, how the official compiler behaves.
