### ISSUE TITLE
Suggested changes

### ISSUE THREAD

**Issue by kaoecoito** [uwol/vb6parser#9]
Hello,
I made some changes that are not errors, but are necessary for my project.

Following is a description of the changes in VisualBasic6.g4.

This change allows the Object.Value expression to the default value of the parameter.
argDefaultValue
   : EQ WS? (literal | ambiguousIdentifier (DOT ambiguousIdentifier)*)
   ;

This change allows the expression Object.value(0)(1).method param
iCS_S_ProcedureOrArrayCall
   : (ambiguousIdentifier | baseType) typeHint? WS? ( LPAREN WS? (argsCall WS?)? RPAREN )+ dictionaryCallStmt?
   ;

// letters

The next change is because my language is Brazilian Portuguese, although we do not recommend to programmers to create variables or methods with accentuation I located this use in several parts of the code.
fragment LETTER
   : [a-zA-Z_äöüÄÖÜáéíóúÁÉÍÓÚâêîôûÂÊÎÔÛàèìòùÀÈÌÒÙãẽĩõũÃẼĨÕŨçÇ]
   ;
fragment LETTERORDIGIT
   : [a-zA-Z0-9_äöüÄÖÜáéíóúÁÉÍÓÚâêîôûÂÊÎÔÛàèìòùÀÈÌÒÙãẽĩõũÃẼĨÕŨçÇ]
   ;

**Comment by uwol** [comment]
Thanks! I implemented the changes suggested by you in commit https://github.com/uwol/vb6parser/commit/a231f5fbe233ebef27f9ef6d39c76cfdabd3b6e1

If you find anything else, please let me know!

**Comment by kaoecoito** [comment]
Thank you. This project will help me a lot.
